---
ci: 
  autofix_prs: true

repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.1.0
    hooks:
      - id: stylua-github
  - repo: local
    hooks:
      - id: check-vim-notify-once
        name: Ensure 'vim.notify' appears exactly once
        entry: scripts/no-vim-notify.sh
        language: script
        files: ^lua/octo/.*\.lua$
        pass_filenames: false
