name: Typecheck

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  typecheck:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        nvim_version: [stable]
        lua_ls_version: [3.15.0]
    steps:
      - uses: actions/checkout@v6
      - name: Install neovim
        run: |
          url="https://github.com/neovim/neovim/releases/download/${{ matrix.nvim_version }}/nvim-linux-x86_64.tar.gz"
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL $url | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
      - name: Install lua-language-server
        run: |
          mkdir -p luals
          curl -L "https://github.com/LuaLS/lua-language-server/releases/download/${{ matrix.lua_ls_version }}/lua-language-server-${{ matrix.lua_ls_version }}-linux-x64.tar.gz" | tar zx --directory luals
      - run: echo "luals/bin" >> "$GITHUB_PATH"
      - name: Checkout dependencies
        run: |
          mkdir -p deps
          DEPS=(
            "nvim-lua/plenary.nvim"
            "folke/snacks.nvim"
            "nvim-telescope/telescope.nvim"
            "ibhagwan/fzf-lua"
            "nvim-tree/nvim-web-devicons"
            "Bilal2453/luvit-meta"
          )
          for dep in "${DEPS[@]}"; do
            repo_name=$(echo $dep | cut -d'/' -f2)
            git clone --depth 1 "https://github.com/${dep}.git" "deps/${repo_name}"
          done
      - name: Typecheck
        run: |
          env VIMRUNTIME=${PWD}/_neovim/share/nvim/runtime lua-language-server --check=${PWD}/lua --configpath=${PWD}/.github/workflows/.luarc.json --checklevel=Information
